### ISSUE TITLE
useing problme

### ISSUE THREAD

**Issue by seamman** [CynricFeng/Papercutting#1]
您好，我也是清华大学，建筑学院的一名在读生，非常喜欢您关于折纸艺术的数字化处理过程，特别想进一步了解其使用内容。奈何本人编程功力极浅，可否指导一二如何使用您的程序？不胜感激

**Comment by fengyangyang98** [comment]
Hi,

这个项目是基于 Mac 端下的 Xcode Playground 编写的。由于 Xcode 更新十分频繁，我也不确定这个项目是否还能在现在最新版本的 Xcode 上运行。

如果你感兴趣，你可以尝试先在 MacOS 上下载一个 Xcode，将此项目作为 Playground 导入到 Xcode 中。如果有什么问题，可以截图给我，或者邮件联系我。

😄

**Comment by seamman** [comment]
非常感谢，我这就再尝试一下。感谢您的回复！
